- name: Install Nginx
  become: yes
  apt: name=nginx state=present

- name: Copy core Nginx configs
  become: yes
  copy: src=conf/ dest=/etc/nginx/ mode=0644 force=yes
  notify:
    - Restart Nginx

- name: Copy default index.html page
  become: yes
  copy: src=index.html dest=/usr/share/nginx/html/index.html owner=www-data group=www-data mode=0644
