# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Common config
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # Setup the primary "app", that'll be the prod system.
  config.vm.define "app", primary: true do |app|
    app.vm.hostname = "dev.murrayjohn.com"
    app.vm.network "private_network", ip: "10.100.119.100"
    app.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "dev/inventory"
      ansible.playbook = "bootstrap.yml"
      ansible.limit = "all"
      ansible.ask_vault_pass = true
      ansible.extra_vars = {
        ansible_user: "vagrant"
      }
      ansible.verbose = "vvvv"
    end
  end
end
